CREATE TABLE `test_application` (
  `ID` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USER` text COLLATE utf8_bin,
  `HOME` text COLLATE utf8_bin,
  `HTTP_ACCEPT_LANGUAGE` text COLLATE utf8_bin,
  `HTTP_ACCEPT_ENCODING` text COLLATE utf8_bin,
  `HTTP_ACCEPT` text COLLATE utf8_bin,
  `HTTP_USER_AGENT` text COLLATE utf8_bin,
  `HTTP_UPGRADE_INSECURE_REQUESTS` text COLLATE utf8_bin,
  `HTTP_CONNECTION` text COLLATE utf8_bin,
  `HTTP_HOST` text COLLATE utf8_bin,
  `REDIRECT_STATUS` text COLLATE utf8_bin,
  `SERVER_NAME` text COLLATE utf8_bin,
  `SERVER_PORT` text COLLATE utf8_bin,
  `SERVER_ADDR` text COLLATE utf8_bin,
  `REMOTE_PORT` text COLLATE utf8_bin,
  `REMOTE_ADDR` text COLLATE utf8_bin,
  `SERVER_SOFTWARE` text COLLATE utf8_bin,
  `GATEWAY_INTERFACE` text COLLATE utf8_bin,
  `REQUEST_SCHEME` text COLLATE utf8_bin,
  `SERVER_PROTOCOL` text COLLATE utf8_bin,
  `DOCUMENT_ROOT` text COLLATE utf8_bin,
  `DOCUMENT_URI` text COLLATE utf8_bin,
  `REQUEST_URI` text COLLATE utf8_bin,
  `SCRIPT_NAME` text COLLATE utf8_bin,
  `CONTENT_LENGTH` text COLLATE utf8_bin,
  `CONTENT_TYPE` text COLLATE utf8_bin,
  `REQUEST_METHOD` text COLLATE utf8_bin,
  `QUERY_STRING` text COLLATE utf8_bin,
  `SCRIPT_FILENAME` text COLLATE utf8_bin,
  `PATH_INFO` text COLLATE utf8_bin,
  `FCGI_ROLE` text COLLATE utf8_bin,
  `PHP_SELF` text COLLATE utf8_bin,
  `REQUEST_TIME_FLOAT` float,
  `REQUEST_TIME` text COLLATE utf8_bin
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;